## Purpose
To make a table that encodes randomization of the different sequences across all subjects and sessions

Problem: making it balanced across runs and sessions

In [26]:
import pandas as pd
import numpy as np
from random import shuffle, choice

In [15]:
block_1 = list(range(2, 7))
block_2 = list(range(7, 12))
block_3 = list(range(12, 17))

# n_runs = 5
run_list = [1, 3, 4, 5, 6]
n_ses = 3
n_subs = 20

design_blocks = [block_1, block_2, block_3]

In [7]:
print(design_blocks)

[[2, 3, 4, 5, 6], [7, 8, 9, 10, 11], [12, 13, 14, 15, 16]]

In [16]:
subs = []
sess = []
runs = []
seqs = []

for sub in range(1, n_subs+1):
#     print(sub)
    group = sub % 3 # groups 0-2
    ses_1 = design_blocks[group]
    ses_2 = design_blocks[(group+1)%3]
    ses_3 = design_blocks[(group+2)%3]
    
#     while unbalanced:
        
    shuffle(ses_1)
    shuffle(ses_2)
    shuffle(ses_3)
#         unbalanced = balance_check()
    
    seq = ses_1 + ses_2 + ses_3

#     run = list(range(1, 6)) * 3
    run = run_list*3
    sub_list = [sub] * len(seq)
    ses_list = [1] * len(ses_1) + [2] * len(ses_2) + [3] * len(ses_3) 
    
    
    subs += sub_list
    sess += ses_list
    seqs += seq
    runs += run

df = pd.DataFrame({'subject':subs, 'ses':sess, 'run':runs, 'seq': seqs})
df.to_csv('seqs_df.csv', index=False)

In [121]:
split_df = df[df.run == 1]
test = split_df.seq.value_counts()
# print(split_df.seq.value_counts())

def balance_check(subs, sess, runs, seqs, ses_1, ses_2, ses_3):
    seq = ses_1 + ses_2 + ses_3

    run = list(range(1, 6)) * 3
    sub_list = [sub] * len(seq)
    ses_list = [1] * len(ses_1) + [2] * len(ses_2) + [3] * len(ses_3) 
    df = pd.DataFrame({'subject':subs, 'ses':sess, 'run':runs, 'seq': seqs})
    
    
    subs += sub_list
    sess += ses_list
    seqs += seq
    runs += run
    for run_id in df.run.unique():
        split_df = df[df.run == run_id]
        split_max = split_df.seq.value_counts().max()
        split_min = split_df.seq.value_counts().min() 
        
        if (split_max > 6) and (split_min < 6) 
    
    pass

def balance_test(test):
    # normalize to dist
    test = test/test.max()
    print(test.mean())
    print(1/2)

test.sum()/len(test)

4.0

In [118]:
t = test/test.sum()
t.mean()

0.06666666666666667

In [ ]:
# balance across sessions: every seq appears 6 or seven times per session
for ses_id in [1, 2, 3]:
    split_df = df[df.ses == ses_id]
    print(split_df.seq.value_counts())

In [ ]:
# balance across subjects: every seq appears once per subject
for sub_id in range(1, n_subs+1):
#     print(sub_id)
    split_df = df[df.subject == sub_id]
    print(split_df.seq.value_counts())

In [ ]:
# balance across runs: every seq appears randomly per run
for run_id in df.run.unique():
    split_df = df[df.run == run_id]
    print(split_df.seq.value_counts())

In [81]:
df.run.unique()

array([1, 2, 3, 4, 5])

In [72]:
60/15

4.0

In [75]:
np.arange(1, 16)#.sum()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
df = pd.read_csv('seqs_df.csv')
# further checking balance across runs
for run_id in df.run.unique():
    split_df = df[(df.run == run_id)]
    
    counts_seq_per_run_id = split_df.seq.value_counts()
    print(counts_seq_per_run_id)
    
    
    for group_id in range(3):

        print(run_id)
        split_df = df[(df.run == run_id) & (df.ses % 3 == group_id)]
#         print(split_df)
        counts_seq_per_run_id = split_df.seq.value_counts()
        print(counts_seq_per_run_id)
#     #     for seq, count in counts_seq_per_run_id.iteritems():
#     #         print(seq, count)
#             for sub in range(1, n_subs+1):
#     #     print(sub)
#         group = sub % 3 # groups 0-2

## HRF

In [12]:
from random import shuffle
iti_sequences =[[12, 11, 13, 13, 11, 14, 14, 15, 12, 15],
                [14, 11, 13, 15, 12, 12, 13, 15, 14, 11],
                [14, 11, 14, 13, 15, 13, 12, 11, 15, 12],
                [12, 12, 11, 15, 11, 14, 15, 13, 14, 13],
                [13, 15, 14, 14, 12, 11, 13, 11, 12, 15],
                [11, 12, 12, 14, 11, 14, 13, 15, 15, 13]]

In [13]:
import yaml

iti_sequences ={0:[12, 11, 13, 13, 11, 14, 14, 15, 12, 15],
                1:[14, 11, 13, 15, 12, 12, 13, 15, 14, 11],
                2:[14, 11, 14, 13, 15, 13, 12, 11, 15, 12],
                3:[12, 12, 11, 15, 11, 14, 15, 13, 14, 13],
                4:[13, 15, 14, 14, 12, 11, 13, 11, 12, 15],
                5:[11, 12, 12, 14, 11, 14, 13, 15, 15, 13]}

with open("hrf_seqs.yaml", "w") as f:
    yaml.dump(iti_sequences, f)

In [15]:
with open("hrf_seqs.yaml", "r") as f:
    loaded_dict = yaml.safe_load(f)
print(loaded_dict[3])

[12, 12, 11, 15, 11, 14, 15, 13, 14, 13]

In [30]:

n_ses = 3
n_subs = 20
runs = [1,2]
iti_ids = [0, 1, 2, 3, 4, 5]

sub_list = []
itis_list = []
run_list = []
ses_list = []
for sub in range(1, n_subs + 1):
    for ses in range(1, n_ses + 1):
        for run in runs:    
            # print(sub, ses)
            # print(runs*n_ses)
            # print(runs)
            sub_list.append(sub)
            ses_list.append(ses)
            run_list.append(run)

    # run_list += runs * n_ses
    shuffle(iti_ids)
    itis_list += iti_ids

print(len(run_list))
print(len(sub_list))
print(len(ses_list))
print(len(itis_list))

df = pd.DataFrame({"subject" : sub_list, 
                   "ses" : ses_list, 
                   "run" : run_list,
                   "seq" : itis_list})
df

120
120
120
120

     subject  ses  run  seq
0          1    1    1    2
1          1    1    2    4
2          1    2    1    5
3          1    2    2    3
4          1    3    1    1
..       ...  ...  ...  ...
115       20    1    2    3
116       20    2    1    4
117       20    2    2    5
118       20    3    1    1
119       20    3    2    2

[120 rows x 4 columns]

In [ ]:
# save
df.to_csv('seqs_df_hrf.csv', index=False)

## Deprecated

In [37]:
n_runs = 6
n_ses = 3
n_subs = 20

seq_ids = [str(i).zfill(3) for i in np.arange(1, n_ses * n_runs + 1)]
sub_ids = [str(i).zfill(2) for i in np.arange(1, n_subs + 1)]
run_ids = [str(i).zfill(2) for i in np.arange(1, n_runs + 1)]
ses_ids = [str(i).zfill(2) for i in np.arange(1, n_ses + 1)]

sub = []
ses = []
run = []
seq = []

for sub_id in sub_ids:
    
    shuffle(seq_ids)
    
    seq += seq_ids
    sub += [sub_id] * (n_runs * n_ses)
    
    for ses_id in ses_ids:
        ses += [ses_id] * n_runs
    
    run += run_ids * 3
    
rand_df = pd.DataFrame({'sub':sub, 'ses':ses, 'run':run, 'seq':seq})
rand_df

    sub ses run  seq
0    01  01  01  016
1    01  01  02  007
2    01  01  03  014
3    01  01  04  011
4    01  01  05  004
..   ..  ..  ..  ...
355  20  03  02  013
356  20  03  03  010
357  20  03  04  015
358  20  03  05  004
359  20  03  06  005

[360 rows x 4 columns]

In [50]:
for i, row in rand_df.iterrows():
    print(row.seq)
    split_df = rand_df[rand_df.ses == ses_id]

    n = split_df.seq.value_counts()[row.seq]
    print(n)
    
    # make random choice
    randomseq_ids

016
7
007
3
014
6
011
7
004
7
017
4
012
6
015
4
010
10
005
9
006
6
018
9
013
7
001
6
003
8
002
9
008
3
009
9
015
4
007
3
004
7
003
8
014
6
008
3
005
9
011
7
012
6
009
9
017
4
013
7
016
7
010
10
006
6
002
9
001
6
018
9
011
7
015
4
004
7
002
9
008
3
009
9
012
6
001
6
013
7
006
6
007
3
003
8
005
9
014
6
016
7
017
4
010
10
018
9
004
7
006
6
008
3
012
6
011
7
001
6
014
6
002
9
007
3
017
4
015
4
013
7
010
10
003
8
005
9
018
9
009
9
016
7
013
7
014
6
004
7
005
9
010
10
011
7
006
6
007
3
008
3
015
4
016
7
001
6
003
8
002
9
012
6
018
9
017
4
009
9
003
8
016
7
012
6
015
4
018
9
007
3
006
6
011
7
017
4
014
6
004
7
002
9
005
9
001
6
013
7
008
3
009
9
010
10
008
3
003
8
001
6
014
6
013
7
011
7
017
4
015
4
018
9
007
3
012
6
006
6
004
7
005
9
002
9
009
9
016
7
010
10
008
3
001
6
013
7
017
4
002
9
010
10
011
7
015
4
004
7
003
8
006
6
007
3
005
9
018
9
016
7
009
9
014
6
012
6
008
3
007
3
006
6
011
7
013
7
014
6
003
8
009
9
016
7
001
6
005
9
018
9
015
4
010
10
012
6
002
9
004
7
017
4
003
8
012
6
009
9
001
6
010
10
004
7
017
4
007
3
013
7
015
4
014
6
008
3
002
9
006
6
005
9
018
9
016
7
011
7
017
4
009
9
005
9
002
9
015
4
006
6
010
10
016
7
007
3
003
8
013
7
004
7
011
7
001
6
008
3
014
6
018
9
012
6
015
4
010
10
011
7
002
9
001
6
016
7
008
3
003
8
017
4
012
6
009
9
018
9
005
9
014
6
013
7
004
7
007
3
006
6
010
10
014
6
012
6
011
7
018
9
013
7
007
3
008
3
009
9
001
6
017
4
016
7
015
4
002
9
006
6
005
9
004
7
003
8
017
4
008
3
007
3
010
10
013
7
015
4
014
6
002
9
005
9
016
7
012
6
003
8
011
7
004
7
018
9
001
6
006
6
009
9
006
6
015
4
001
6
004
7
005
9
010
10
008
3
009
9
007
3
016
7
017
4
012
6
011
7
018
9
003
8
002
9
013
7
014
6
008
3
006
6
018
9
011
7
016
7
005
9
002
9
012
6
009
9
007
3
001
6
013
7
010
10
017
4
003
8
015
4
014
6
004
7
014
6
017
4
018
9
005
9
016
7
015
4
008
3
013
7
009
9
010
10
004
7
012
6
007
3
006
6
001
6
011
7
003
8
002
9
014
6
006
6
007
3
004
7
017
4
018
9
002
9
005
9
015
4
001
6
008
3
016
7
012
6
010
10
011
7
003
8
013
7
009
9
017
4
002
9
018
9
009
9
014
6
015
4
006
6
008
3
001
6
005
9
003
8
004
7
016
7
007
3
012
6
010
10
013
7
011
7
008
3
012
6
003
8
011
7
001
6
016
7
002
9
006
6
018
9
017
4
007
3
014
6
009
9
013
7
010
10
015
4
004
7
005
9

In [46]:
# check balance across sessions
for ses_id in ses_ids:
    split_df = rand_df[rand_df.ses == ses_id]
    print(split_df.seq.value_counts())

011    10
014     9
015     9
008     9
004     8
017     7
010     7
001     7
016     6
006     6
013     6
018     6
007     6
012     5
005     5
003     5
002     5
009     4
Name: seq, dtype: int64
007    11
012     9
017     9
008     8
006     8
015     7
016     7
003     7
001     7
013     7
009     7
002     6
005     6
018     5
014     5
004     5
011     3
010     3
Name: seq, dtype: int64
010    10
018     9
005     9
002     9
009     9
003     8
011     7
004     7
013     7
016     7
001     6
006     6
014     6
012     6
017     4
015     4
008     3
007     3
Name: seq, dtype: int64

In [39]:
# check balance across runs
for run_id in run_ids:
    split_df = rand_df[rand_df.run == run_id]
    print(split_df.seq.value_counts())

008    8
005    5
011    5
017    5
015    4
014    4
010    4
006    4
003    4
002    4
016    3
012    3
013    2
004    2
007    2
009    1
Name: seq, dtype: int64
007    6
006    6
001    5
002    5
015    5
010    4
014    4
009    3
003    3
008    3
012    3
017    2
016    2
018    2
005    2
011    2
013    2
004    1
Name: seq, dtype: int64
012    6
018    6
007    5
013    5
009    4
003    4
004    4
005    4
001    4
006    3
016    3
008    3
010    2
017    2
011    2
014    1
002    1
015    1
Name: seq, dtype: int64
002    7
011    6
001    5
005    5
015    5
003    4
009    4
017    4
010    3
004    3
018    3
014    3
007    2
012    2
016    2
008    1
006    1
Name: seq, dtype: int64
013    7
004    6
014    5
017    5
016    5
001    4
008    3
007    3
010    3
006    3
009    3
018    3
012    2
005    2
015    2
003    2
002    1
011    1
Name: seq, dtype: int64
018    6
009    5
016    5
012    4
013    4
004    4
011    4
010    4
015    3
003    3
014    3
006    3
017    2
007    2
002    2
001    2
008    2
005    2
Name: seq, dtype: int64

In [65]:
import random

# Define parameters
num_subjects = 20
num_sessions = 3
num_items = 18
items_per_session = 6
target_total_per_item = num_subjects  # Each item should appear 20 times total
target_per_session = target_total_per_item // num_sessions  # Roughly 7 per session

# Initialize counters
total_item_counts = {item: 0 for item in range(num_items)}
session_item_counts = [{item: 0 for item in range(num_items)} for _ in range(num_sessions)]

# Initialize storage for results
subjects_sessions = []

# Assign items per subject and session
for subject in range(num_subjects):
    subject_sessions = []
    used_items = set()  # Track items already used by the subject

    for session in range(num_sessions):
        session_items = []
        while len(session_items) < items_per_session:
            item = random.choice(range(num_items))

            # Check if the item can be assigned without breaking balance
            if (total_item_counts[item] < target_total_per_item and
                session_item_counts[session][item] < target_per_session + 1 and  # Allow some leeway
                item not in used_items):

                # Assign item
                session_items.append(item)
                used_items.add(item)
                total_item_counts[item] += 1
                session_item_counts[session][item] += 1

        subject_sessions.append(session_items)

    subjects_sessions.append(subject_sessions)

# Display the result for each subject
for subject, sessions in enumerate(subjects_sessions):
    print(f"Subject {subject + 1}:")
    for session, items in enumerate(sessions):
        print(f"  Session {session + 1}: Items {items}")

KeyboardInterrupt: